https://g.co/gemini/share/49c6aa3f203fname: Test everything

on: [push,pull_request]

jobs:
  build:

    

    strategy:
      matrix:
        system: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      

      - run: yarn install
        continue-on-error: true
      - run: yarn build
        continue-on-error: true
      - run: yarn run test_all
        continue-on-error: true
